language: ruby

rvm:
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9"

sudo: false

install:
  - travis_retry bundle install -j4 --path vendor/bundle

script:
  - bundle exec rake spec

deploy:
  provider: rubygems
  api_key:
    master:
      secure: "IglhEWHd45IzaY7aCjIZz5LOU3IxzpJFerRfgTwKRZYLARjgtkkzARbAJ1PsnurtMdYA+aMHUiGPSgclMb+gLSXGjD1e+mx6cY0b7k4r7c8heFdKbnHIaC438fKqlqCew8oDsL1MACJO+2sZZClktnFRJnlVyQUxOaPQ0SmDzMQ="
  gem:
    master: social_snippet-supports-github
  on:
    repo: social-snippet/social-snippet-supports-github
    ruby: "2.2"

cache:
  directories:
    - vendor/bundle

